# This is a basic workflow to help you get started with Actions

name: Firt Aderly Workflow

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "First command"
          echo "Second Command"
          echo "This will run both commands in one step"
      - name: Print goodbye
        run: echo "Done.  Bye.!"
